### ISSUE TITLE
chrome使用技巧

### ISSUE THREAD

**Issue by liushengqi000** [lighthouse-853/AO3-Google-Mirror#3]
chromium系列桌面浏览器（chrome/edge/...）加上启动参数
`--host-resolver-rules='MAP fanlore.org 208.85.241.152' --host-rules='MAP archiveofourown.org fanlore.org,MAP *.archiveofourown.org fanlore.org'`
可直连https://archiveofourown.org

**Comment by youchen-0** [comment]
搞笑
墙要是只有dns污染的话那dns加密早就火了

**Comment by liushengqi000** [comment]
> 搞笑 墙要是只有dns污染的话那dns加密早就火了

建议你仔细研究 --host-rules
